spring.application.name=stin-currency-app
spring.profiles.active=prod
settings.file.path=${SETTINGS_PATH:user-settings.json}
logging.file.path=${LOG_DIR:logs}
logging.file.name=${LOG_PATH:logs/app.log}
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
spring.security.user.name=${API_USERNAME}
spring.security.user.password=${API_PASSWORD}
spring.security.user.roles=USER
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
api.exchangerate.base-url=https://api.exchangerate.host
api.exchangerate.key=${EXCHANGE_API_KEY}